name: life_controll_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  fl_chart: ^0.55.2
  animations: ^2.0.7
  flutter_bloc: ^8.1.1
  table_calendar: ^3.0.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/drawer_header.svg
    - lib/assets/drawer_header.jpg
    - lib/assets/unkn.jpg
    - lib/assets/unkn2.jpg
    - lib/assets/unkn3.jpg
    - lib/assets/unkn4.png